spring:
  application:
    name: template
  profiles:
    active: @spring.profiles.active@

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8181
  servlet:
    context-path: /
